### PR TITLE
Demo config api

### PR DESCRIPTION
**Pull request by aguibert**
PR for issue #160 

Includes initial commit + review comments from PR #161.  Since @susanodom will be on vacation until after JavaOne, I'm making this PR on her behalf.

### CODE REVIEW

**Comment by aguibert** [comment]
@Emily-Jiang please review.

I'm not sure why the ip-validation check is giving me issues.  I am using the exact same Signed-off-by footer as my other PRs which passed validation just fine.  I even went to https://accounts.eclipse.org/user/373291/eca and used the ECA tester and it confirmed that the email I am using in the signoff has a valid ECA.

**Comment by Emily-Jiang** [comment]
@aguibert when you commit, you need to make sure use -s to get the signoff logged.

**Comment by aguibert** [comment]
I committed with `--signoff`, and verified that the signoff header was present in my commit message:

```
Update liberty and microprofile-config dependency coords
Signed-off-by: Andrew Guibert <aguibert@us.ibm.com>
```

**Comment by Emily-Jiang** [comment]
Did you put your github id in your eclipse account profile?

**Comment by aguibert** [comment]
No, but it worked fine before, this commit was merged in OK in a previous PR:
https://github.com/eclipse/microprofile-conference/pull/163/commits/9b6ec98eef9d3aae969e892a39357b0a32209ef1

Will check the eclipse website to see if I can link up to my github id to eclipse account.

**Comment by aguibert** [comment]
Made a new PR that no longer has the ECA validation issue: https://github.com/eclipse/microprofile-conference/pull/172

**Pull request closed without merging**
