### PR TITLE
Kevin patch 2

### PR DESCRIPTION
**Pull request by kwsutter**
Let's try this again after the merge of @heiko-braun patch #156.  Modified the associated tests to make the changes stick.

### CODE REVIEW

**Comment by heiko-braun** [comment]
@kwsutter I wonder if it would be better to retrieve the bootstrap data (speakers in this case) from the `demo-boostrap` module, like in https://github.com/eclipse/microprofile-conference/blob/master/microservice-schedule/src/main/java/io/microprofile/showcase/schedule/persistence/ScheduleDAO.java#L55. This could replace the usage of yet another dataset (`ConferenceData.json`) in the speaker-service. Or do i miss something?

**Comment by heiko-braun** [comment]
We do also need to verify the entity references (foreign keys) between services are consistent. For instance the session service has references to speakers.

**Comment by kwsutter** [comment]
@heiko-braun, I was just taking the easy route on this update...  There used to be a file called JavaOne2016.json which contained data from Oracle's JavaOne conference (similar to the schedule.json file you updated).  So, I followed the same schema in the JavaOne2016.json doc and created ConferenceData.json.  That was the intent of this PR.

**Comment by kwsutter** [comment]
I agree that maybe we could consolidate this "conference data" all in one location, but let's just open a new Issue to clean all of that up.  I'm just looking to get the basics cleaned up so that we can completed our IP review.

**Pull request merged**
