### PR TITLE
Update microprofile-session to Thorntail

### PR DESCRIPTION
**Pull request by xstefank**
I have a student which will be transforming this project (microprofile-session) to the Quarkus runtime. However, the original WildFly swarm based service no longer compiles so I moved it to Thorntail (updated WildFly swarm) so the student can work with it.

### CODE REVIEW

**Comment by kenfinnigan** [comment]
Looks like TravisCI build is broken

**Comment by xstefank** [comment]
However, a strange error - https://travis-ci.com/github/eclipse/microprofile-conference/builds/157285620. We are still based on JDK 8 so why should Travis expect 9 to 15? :)

However, the build will still fail on other modules being outdated, unfortunately. I will try to find some time to update those also. I would like to merge this as is now. Locally passing with JDK 8.

**Comment by xstefank** [comment]
I tried to get approval from different participants but unsuccessfully yet. I will merge this because the student needs to start working on it. If there is any issue found later I will submit a new PR. Sorry for any inconvenience.

**Comment by Emily-Jiang** [comment]
@xstefank just an ack to say that your changes are good.

**Comment by xstefank** [comment]
thanks @Emily-Jiang :)

**Pull request merged**
