### PR TITLE
Remove duplicated line

### PR DESCRIPTION
**Pull request by brunoborges**

### CODE REVIEW

**Comment by cesarhernandezgt** [comment]
@brunoborges , in order to pass the ip-validation, you just need to append to your commit message something like: 
`Signed-off-by: YourGitHubUsername <YourEmailUsedForThisGitRepo>`

**Comment by brunoborges** [comment]
Signed-off-by: brunoborges <bruno.borges@gmail.com>

**Comment by brunoborges** [comment]
Signed-off-by: brunoborges bruno.borges@microsoft.com

**Comment by mikecroft** [comment]
The easiest way is to make sure the problem commit is the most recent one, then run this command:

```
git commit --amend -s
```

It will reopen the previous commit message and automatically add your name/email in the correct format. Then you can just save and push your commit again.

**Comment by brunoborges** [comment]
Will reopen.

**Pull request closed without merging**
